services:
  master:
    image: itzg/mc-proxy
    ports:
      - "27425:27425" # Velocity
      - "27425:27425/UDP" # Simple VoiceChat 
      - "27426:27426" # Multipaper master

    volumes:
      - /srv/minecraft/multipaper/master:/server
      - /srv/minecraft/multipaper/config/forwarding.secret:/config/forwarding.secret:ro
      - /srv/minecraft/multipaper/config/init.sh:/init.sh:ro
      - /srv/minecraft/multipaper/config/yq_linux_amd64:/tmp/yq    

    entrypoint: ["/bin/bash", "-c", "/bin/bash /init.sh master && /bin/bash /usr/bin/run-bungeecord.sh"]
    environment:
      TYPE: VELOCITY
      BUNGEE_JAR_REVISION: "1"
      TZ: Europe/London
      INIT_MEMORY: 512M
      MAX_MEMORY: 2G
      EULA: "TRUE"
      NETWORKADDRESS_CACHE_TTL: 600
      SERVER_PORT: 27425

    stdin_open: true
    tty: true
    networks:
      mpaper:
        ipv4_address: 172.16.238.2

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27429:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: jmhzeolbJwD7Fzh3ZakQ4Cemap23gklA
    volumes:
      - /srv/minecraft/multipaper/mongo:/data/db
    stdin_open: true
    tty: true
    networks:
      mpaper:
        ipv4_address: 172.16.238.3

  node-1:
    image: itzg/minecraft-server
    ports:
      - "27427:27427"
      - "27427:27427/UDP"
    volumes:
      - /srv/minecraft/multipaper/node-1:/data
      - /srv/minecraft/multipaper/config/init.sh:/init.sh:ro
      - /srv/minecraft/multipaper/config/forwarding.secret:/config/forwarding.secret:ro
      - /srv/minecraft/multipaper/config/yq_linux_amd64:/tmp/yq
      - /srv/minecraft/multipaper/master:/master
      - /srv/minecraft/multipaper/config/rclone:/tmp/rclone

    entrypoint: ["/bin/bash", "-c", "/bin/bash /init.sh node-1 && /start"]
    environment:
      TZ: Europe/London
      TYPE: CUSTOM
      CUSTOM_SERVER: https://api.multipaper.io/v2/projects/multipaper/versions/1.20.1/builds/56/downloads/multipaper-1.20.1-56.jar
      JVM_OPTS: |
        -DmultipaperMasterAddress=172.16.238.2:27426
        -Dproperties.view-distance=16
        -Dmultipaper.sync-settings.files.files-to-sync-in-real-time=ops.json,whitelist.json
      EULA: "TRUE"
      MEMORY: 8G
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "true"
      SERVER_PORT: 27427
      GUI: "false"
      DIFFICULTY: normal
    depends_on:
      - master
    working_dir: /data
    stdin_open: true
    tty: true
    networks:
      mpaper:
        ipv4_address: 172.16.238.4

  node-2:
    image: itzg/minecraft-server
    ports:
      - "27428:27428"
      - "27428:27428/UDP"
    volumes:
      - /srv/minecraft/multipaper/node-2:/data
      - /srv/minecraft/multipaper/config/init.sh:/init.sh:ro
      - /srv/minecraft/multipaper/config/forwarding.secret:/config/forwarding.secret:ro
      - /srv/minecraft/multipaper/config/yq_linux_amd64:/tmp/yq
      - /srv/minecraft/multipaper/master:/master
      - /srv/minecraft/multipaper/config/rclone:/tmp/rclone

    entrypoint: ["/bin/bash", "-c", "/bin/bash /init.sh node-2 && /start"]
    environment:
      TZ: Europe/London
      TYPE: CUSTOM
      CUSTOM_SERVER: https://api.multipaper.io/v2/projects/multipaper/versions/1.20.1/builds/56/downloads/multipaper-1.20.1-56.jar
      JVM_OPTS: |
        -DmultipaperMasterAddress=172.16.238.2:27426
        -Dproperties.view-distance=16
        -Dmultipaper.sync-settings.files.files-to-sync-in-real-time=ops.json,whitelist.json
      EULA: "TRUE"      
      MEMORY: 8G
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "true"
      SERVER_PORT: 27428
      GUI: "false"
      DIFFICULTY: normal
    depends_on:
      - master
    working_dir: /data
    stdin_open: true
    tty: true
    networks:
      mpaper:
        ipv4_address: 172.16.238.5

networks:
  mpaper:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24